import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '../config/material-tailwind-theme-provider';
import ReactQueryClientProvider from '@/config/ReactQueryClientProvider';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Netflix',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<ReactQueryClientProvider>
			<ThemeProvider>
				<html lang='en'>
					<head>
						<link
							rel='stylesheet'
							href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css'
							integrity='sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=='
							crossOrigin='anonymous'
							referrerPolicy='no-referrer'
						/>
					</head>
					<body className={inter.className}>
						<Header />
						<main className='py-20'>{children}</main>
						<Footer />
					</body>
				</html>
			</ThemeProvider>
		</ReactQueryClientProvider>
	);
}
