import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '../config/material-tailwind-theme-provider';
import ReactQueryClientProvider from '@/config/ReactQueryClientProvider';
import { ReactNode } from 'react';
import MainLayout from '@/components/layouts/main-layout';
import AuthLayout from '@/components/layouts/auth-layout';
import { createServerSupabaseClient } from '@/utils/supabase/server';
import AuthProvider from '@/config/auth-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Instagram',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	const supabase = await createServerSupabaseClient();
	const {
		data: { session },
	} = await supabase.auth.getSession();

	return (
		<ReactQueryClientProvider>
			<ThemeProvider>
				<html lang='en'>
					<head>
						<link
							rel='stylesheet'
							href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css'
							integrity='sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=='
							crossOrigin='anonymous'
							referrerPolicy='no-referrer'
						/>
					</head>
					<AuthProvider accessToken={session?.access_token}>
						<body className={inter.className}>
							{session?.user ? <MainLayout>{children}</MainLayout> : <AuthLayout />}
						</body>
					</AuthProvider>
				</html>
			</ThemeProvider>
		</ReactQueryClientProvider>
	);
}
