import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '../config/material-tailwind-theme-provider'
import ReactQueryClientProvider from '@/config/ReactQueryClientProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <ThemeProvider>
        <html lang='en'>
          <head>
            <link
              rel='stylesheet'
              href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css'
              integrity='sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg=='
              crossOrigin='anonymous'
              referrerPolicy='no-referrer'
            />
          </head>
          <body className={inter.className}>{children}</body>
        </html>
      </ThemeProvider>
    </ReactQueryClientProvider>
  );
}
